file1=open("file1","w")
l=["this i s delhi \n","this is paris\n","this is london \n"]
file1.writelines(l)
file1.close()
file1=open("file1","r")
print("output ofreadlines before appending:")
print(file1.read())
print()
file1=open("file1","a")
file1.write("today \n")
file1.close()
file1=open("file1","r")
print("outut of readlines after appending:")
print(file1.read())
print()
file1.close()